INSERT INTO news_news (id, title, content, created_at, updated_at, photo, is_published, category_id, views) VALUES (1, 'Novost 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at iaculis lectus. Nunc id ligula est. In placerat commodo ipsum at mollis. Fusce lectus eros, dictum ac varius ac, maximus sed mi. Nulla ac volutpat ante. Donec nec aliquam nibh, quis tristique eros. Curabitur quam turpis, venenatis a tortor nec, venenatis elementum ipsum. Maecenas auctor nunc ac aliquet venenatis. Ut nec velit dui. Ut egestas, enim sed ultrices cursus, turpis nisi dictum diam, sagittis posuere mauris urna eu sem.

Nam a semper velit. Nam nunc magna, condimentum vel auctor eget, accumsan nec purus. Vestibulum vel ligula eleifend quam elementum vestibulum a eget purus. Donec fringilla maximus placerat. Quisque volutpat nibh nec enim dapibus, in scelerisque lectus placerat. Vestibulum efficitur enim et magna porttitor auctor. Nam gravida sem ut orci venenatis, id suscipit purus malesuada. Donec a dictum mi. Pellentesque lobortis magna in lacus dictum, nec auctor odio consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam at volutpat purus, vel lacinia elit.

Cras gravida, sem non viverra posuere, urna neque commodo est, dignissim congue velit eros id turpis. Phasellus quis libero dapibus, tempus dui vel, sodales turpis. Aliquam feugiat, nulla nec sagittis elementum, sapien erat ornare felis, id mattis ipsum eros eu libero. Fusce egestas sed orci sit amet semper. In velit metus, suscipit non aliquam id, consectetur nec neque. Nunc sed consectetur purus. Mauris consequat non dolor quis aliquam. Donec euismod ante dolor, sit amet tempus metus cursus fringilla. Sed rhoncus dignissim lacus, ac posuere urna euismod vel. Nulla ac enim quis ligula consectetur iaculis ac volutpat turpis. Maecenas eros dui, tempus in lorem non, luctus lobortis est. Ut eleifend quam sem, quis placerat mi aliquam eget. Maecenas tellus nisi, fringilla id blandit eget, faucibus nec sem. Sed hendrerit bibendum velit at ullamcorper.', '2020-11-17 00:35:58.276911', '2020-11-29 18:11:12.368553', '', 1, 1, 1);
INSERT INTO news_news (id, title, content, created_at, updated_at, photo, is_published, category_id, views) VALUES (2, 'Novost 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at iaculis lectus. Nunc id ligula est. In placerat commodo ipsum at mollis. Fusce lectus eros, dictum ac varius ac, maximus sed mi. Nulla ac volutpat ante. Donec nec aliquam nibh, quis tristique eros. Curabitur quam turpis, venenatis a tortor nec, venenatis elementum ipsum. Maecenas auctor nunc ac aliquet venenatis. Ut nec velit dui. Ut egestas, enim sed ultrices cursus, turpis nisi dictum diam, sagittis posuere mauris urna eu sem.

Nam a semper velit. Nam nunc magna, condimentum vel auctor eget, accumsan nec purus. Vestibulum vel ligula eleifend quam elementum vestibulum a eget purus. Donec fringilla maximus placerat. Quisque volutpat nibh nec enim dapibus, in scelerisque lectus placerat. Vestibulum efficitur enim et magna porttitor auctor. Nam gravida sem ut orci venenatis, id suscipit purus malesuada. Donec a dictum mi. Pellentesque lobortis magna in lacus dictum, nec auctor odio consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam at volutpat purus, vel lacinia elit.

Cras gravida, sem non viverra posuere, urna neque commodo est, dignissim congue velit eros id turpis. Phasellus quis libero dapibus, tempus dui vel, sodales turpis. Aliquam feugiat, nulla nec sagittis elementum, sapien erat ornare felis, id mattis ipsum eros eu libero. Fusce egestas sed orci sit amet semper. In velit metus, suscipit non aliquam id, consectetur nec neque. Nunc sed consectetur purus. Mauris consequat non dolor quis aliquam. Donec euismod ante dolor, sit amet tempus metus cursus fringilla. Sed rhoncus dignissim lacus, ac posuere urna euismod vel. Nulla ac enim quis ligula consectetur iaculis ac volutpat turpis. Maecenas eros dui, tempus in lorem non, luctus lobortis est. Ut eleifend quam sem, quis placerat mi aliquam eget. Maecenas tellus nisi, fringilla id blandit eget, faucibus nec sem. Sed hendrerit bibendum velit at ullamcorper.', '2020-11-17 00:45:07.643586', '2020-11-26 06:06:07.984646', '', 1, 1, 0);
INSERT INTO news_news (id, title, content, created_at, updated_at, photo, is_published, category_id, views) VALUES (3, 'Novost 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at iaculis lectus. Nunc id ligula est. In placerat commodo ipsum at mollis. Fusce lectus eros, dictum ac varius ac, maximus sed mi. Nulla ac volutpat ante. Donec nec aliquam nibh, quis tristique eros. Curabitur quam turpis, venenatis a tortor nec, venenatis elementum ipsum. Maecenas auctor nunc ac aliquet venenatis. Ut nec velit dui. Ut egestas, enim sed ultrices cursus, turpis nisi dictum diam, sagittis posuere mauris urna eu sem.

Nam a semper velit. Nam nunc magna, condimentum vel auctor eget, accumsan nec purus. Vestibulum vel ligula eleifend quam elementum vestibulum a eget purus. Donec fringilla maximus placerat. Quisque volutpat nibh nec enim dapibus, in scelerisque lectus placerat. Vestibulum efficitur enim et magna porttitor auctor. Nam gravida sem ut orci venenatis, id suscipit purus malesuada. Donec a dictum mi. Pellentesque lobortis magna in lacus dictum, nec auctor odio consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam at volutpat purus, vel lacinia elit.

Cras gravida, sem non viverra posuere, urna neque commodo est, dignissim congue velit eros id turpis. Phasellus quis libero dapibus, tempus dui vel, sodales turpis. Aliquam feugiat, nulla nec sagittis elementum, sapien erat ornare felis, id mattis ipsum eros eu libero. Fusce egestas sed orci sit amet semper. In velit metus, suscipit non aliquam id, consectetur nec neque. Nunc sed consectetur purus. Mauris consequat non dolor quis aliquam. Donec euismod ante dolor, sit amet tempus metus cursus fringilla. Sed rhoncus dignissim lacus, ac posuere urna euismod vel. Nulla ac enim quis ligula consectetur iaculis ac volutpat turpis. Maecenas eros dui, tempus in lorem non, luctus lobortis est. Ut eleifend quam sem, quis placerat mi aliquam eget. Maecenas tellus nisi, fringilla id blandit eget, faucibus nec sem. Sed hendrerit bibendum velit at ullamcorper.', '2020-11-17 00:46:43.784959', '2020-11-26 06:06:07.975766', '', 1, 2, 120);
INSERT INTO news_news (id, title, content, created_at, updated_at, photo, is_published, category_id, views) VALUES (4, 'News 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at iaculis lectus. Nunc id ligula est. In placerat commodo ipsum at mollis. Fusce lectus eros, dictum ac varius ac, maximus sed mi. Nulla ac volutpat ante. Donec nec aliquam nibh, quis tristique eros. Curabitur quam turpis, venenatis a tortor nec, venenatis elementum ipsum. Maecenas auctor nunc ac aliquet venenatis. Ut nec velit dui. Ut egestas, enim sed ultrices cursus, turpis nisi dictum diam, sagittis posuere mauris urna eu sem.

Nam a semper velit. Nam nunc magna, condimentum vel auctor eget, accumsan nec purus. Vestibulum vel ligula eleifend quam elementum vestibulum a eget purus. Donec fringilla maximus placerat. Quisque volutpat nibh nec enim dapibus, in scelerisque lectus placerat. Vestibulum efficitur enim et magna porttitor auctor. Nam gravida sem ut orci venenatis, id suscipit purus malesuada. Donec a dictum mi. Pellentesque lobortis magna in lacus dictum, nec auctor odio consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam at volutpat purus, vel lacinia elit.

Cras gravida, sem non viverra posuere, urna neque commodo est, dignissim congue velit eros id turpis. Phasellus quis libero dapibus, tempus dui vel, sodales turpis. Aliquam feugiat, nulla nec sagittis elementum, sapien erat ornare felis, id mattis ipsum eros eu libero. Fusce egestas sed orci sit amet semper. In velit metus, suscipit non aliquam id, consectetur nec neque. Nunc sed consectetur purus. Mauris consequat non dolor quis aliquam. Donec euismod ante dolor, sit amet tempus metus cursus fringilla. Sed rhoncus dignissim lacus, ac posuere urna euismod vel. Nulla ac enim quis ligula consectetur iaculis ac volutpat turpis. Maecenas eros dui, tempus in lorem non, luctus lobortis est. Ut eleifend quam sem, quis placerat mi aliquam eget. Maecenas tellus nisi, fringilla id blandit eget, faucibus nec sem. Sed hendrerit bibendum velit at ullamcorper.', '2020-11-17 00:48:15.886512', '2020-11-30 12:06:28.497447', 'photos/2020/11/30/Forza-Horizon-4-car-video-games-Adobe-Porsche-911-Carrera-S-1910623.jpg', 1, 3, 0);
INSERT INTO news_news (id, title, content, created_at, updated_at, photo, is_published, category_id, views) VALUES (5, 'News 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at iaculis lectus. Nunc id ligula est. In placerat commodo ipsum at mollis. Fusce lectus eros, dictum ac varius ac, maximus sed mi. Nulla ac volutpat ante. Donec nec aliquam nibh, quis tristique eros. Curabitur quam turpis, venenatis a tortor nec, venenatis elementum ipsum. Maecenas auctor nunc ac aliquet venenatis. Ut nec velit dui. Ut egestas, enim sed ultrices cursus, turpis nisi dictum diam, sagittis posuere mauris urna eu sem.

Nam a semper velit. Nam nunc magna, condimentum vel auctor eget, accumsan nec purus. Vestibulum vel ligula eleifend quam elementum vestibulum a eget purus. Donec fringilla maximus placerat. Quisque volutpat nibh nec enim dapibus, in scelerisque lectus placerat. Vestibulum efficitur enim et magna porttitor auctor. Nam gravida sem ut orci venenatis, id suscipit purus malesuada. Donec a dictum mi. Pellentesque lobortis magna in lacus dictum, nec auctor odio consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam at volutpat purus, vel lacinia elit.

Cras gravida, sem non viverra posuere, urna neque commodo est, dignissim congue velit eros id turpis. Phasellus quis libero dapibus, tempus dui vel, sodales turpis. Aliquam feugiat, nulla nec sagittis elementum, sapien erat ornare felis, id mattis ipsum eros eu libero. Fusce egestas sed orci sit amet semper. In velit metus, suscipit non aliquam id, consectetur nec neque. Nunc sed consectetur purus. Mauris consequat non dolor quis aliquam. Donec euismod ante dolor, sit amet tempus metus cursus fringilla. Sed rhoncus dignissim lacus, ac posuere urna euismod vel. Nulla ac enim quis ligula consectetur iaculis ac volutpat turpis. Maecenas eros dui, tempus in lorem non, luctus lobortis est. Ut eleifend quam sem, quis placerat mi aliquam eget. Maecenas tellus nisi, fringilla id blandit eget, faucibus nec sem. Sed hendrerit bibendum velit at ullamcorper.', '2020-11-17 00:49:47.443858', '2020-11-21 06:54:03.529664', '', 1, 4, 6);
INSERT INTO news_news (id, title, content, created_at, updated_at, photo, is_published, category_id, views) VALUES (13, 'news from site', 'Hello from site', '2020-11-24 14:17:58.557151', '2020-11-24 14:17:58.557151', '', 1, 4, 78);
INSERT INTO news_news (id, title, content, created_at, updated_at, photo, is_published, category_id, views) VALUES (14, 'news from site 2', 'Hello world guys', '2020-11-24 14:37:39.922736', '2020-11-24 14:37:39.922736', '', 1, 4, 1200);
INSERT INTO news_news (id, title, content, created_at, updated_at, photo, is_published, category_id, views) VALUES (15, 'the 6 news', 'content 6', '2020-11-26 04:38:22.650822', '2020-11-26 05:47:58.834231', '', 1, 4, 78);
INSERT INTO news_news (id, title, content, created_at, updated_at, photo, is_published, category_id, views) VALUES (17, 'News 7', 'News for CLASSVIEWs', '2020-11-26 07:07:27.316949', '2020-11-26 07:07:27.316949', '', 1, 1, 500);
INSERT INTO news_news (id, title, content, created_at, updated_at, photo, is_published, category_id, views) VALUES (18, 'News 8', 'news 8', '2020-11-26 07:14:23.020229', '2020-11-26 07:14:23.020229', '', 1, 1, 1);